In [58]:
# Importação das bibliotecas necessárias
import pandas as pd
import numpy as np
import psycopg2
import math
from datetime import datetime
import sys
import os
import openpyxl
import boto3
from io import BytesIO
from sqlalchemy import create_engine

In [60]:
pd.set_option("display.max_columns", None)

In [62]:
nome_empresa = input("Digite o nome da empresa: ")

if nome_empresa.lower() == 'tateti':
    cnpj = "65369985000504"
    cnpj_produtos = "65369985000334"
    cnpjs = [cnpj]

if nome_empresa.lower() == 'ladakh':
    cnpj = "07318052000150"
    cnpj_produtos = "07318052000150"
    cnpjs = [cnpj]

if nome_empresa.lower() == 'sonda':
    cnpj = "01937635001316"
    cnpj_produtos = "01937635001316"
    cnpjs = [cnpj]

engine = create_engine(
    f"postgresql+psycopg2://cat:5pM2h0MBQu9JHkxHud2A@177.11.49.194:3361/4btaxtech"
)

# Variáveis para acesso ao s3
bucket_name = '4btaxtech'

s3 = boto3.client('s3', 
                  aws_access_key_id='AKIA4RCAOBRSFONXEUTE', 
                  aws_secret_access_key='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',
                  region_name='us-east-1'
                  )

print("✅ Cliente S3 autenticado com sucesso!")

Digite o nome da empresa:  ladakh

✅ Cliente S3 autenticado com sucesso!

In [64]:
def ler_arquivo_para_dataframe(bucket_name, s3_key, file_type='csv', sep=None):
    """
    Lê um arquivo do S3 e carrega em um DataFrame do Pandas.
    
    :param bucket_name: Nome do bucket.
    :param s3_key: Caminho do arquivo no S3.
    :param file_type: Tipo do arquivo ('csv' ou 'xlsx').
    :return: DataFrame do Pandas.
    """
    try:
        response = s3.get_object(Bucket=bucket_name, Key=s3_key)
        if file_type == 'csv':
            df = pd.read_csv(BytesIO(response['Body'].read()), dtype=str, header=0, sep=sep)
        elif file_type == 'xlsx':
            df = pd.read_excel(BytesIO(response['Body'].read()))
        else:
            raise ValueError("Tipo de arquivo não suportado. Use 'csv' ou 'xlsx'.")
        print(f"Arquivo '{s3_key}' lido com sucesso!")
        return df
    except Exception as e:
        print(f"Erro ao ler arquivo do S3: {e}")
        return None
    
def salvar_dataframe_no_s3(df, bucket_name, s3_key, file_type='csv'):
    """
    Salva um DataFrame do Pandas no S3.
    
    :param df: DataFrame a ser salvo.
    :param bucket_name: Nome do bucket.
    :param s3_key: Caminho para salvar o arquivo no S3.
    :param file_type: Tipo do arquivo ('csv' ou 'xlsx').
    """
    try:
        buffer = BytesIO()
        if file_type == 'csv':
            df.to_csv(buffer, index=False, encoding='utf-8')
        elif file_type == 'xlsx':
            with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
                df.to_excel(writer, index=False)
        else:
            raise ValueError("Tipo de arquivo não suportado. Use 'csv' ou 'xlsx'.")
        
        buffer.seek(0)  # Resetar o ponteiro do buffer
        s3.put_object(Bucket=bucket_name, Key=s3_key, Body=buffer.getvalue())
        print(f"Arquivo salvo com sucesso em '{s3_key}'.")
    except Exception as e:
        print(f"Erro ao salvar arquivo no S3: {e}")

In [66]:
def baixar_arquivo(bucket_name, s3_key, local_file_name):
    try:
        s3.download_file(bucket_name, s3_key, local_file_name)
        print(f"Arquivo '{s3_key}' baixado como '{local_file_name}'.")
    except Exception as e:
        print(f"Erro ao baixar arquivo: {e}")

baixar_arquivo(bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
               local_file_name=f'ficha_3_{nome_empresa}_{cnpj}_v2.xlsx')

Erro ao baixar arquivo: An error occurred (404) when calling the HeadObject operation: Not Found

In [67]:
colunas = ['Código da Mercadoria', 'Número da Ordem', 'Data', 'Chave', 'Tipo', 'Série do documento', 'Número da nota',
            'Código do Remetente ou Destinatário', 'CFOP', 'Número do Item no Documento XML', 'Quantidade (Entrada)',
            'Valor Total do ICMS Suportado na Retenção ou Antecipação por ST', 'Quantidade (Saída)',
            'Valor Unitário do ICMS Suportado', 'Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1',
            'Fato Gerador Não Realizado - Código Enquadramento Legal = 2', 
            'Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3',
            'Saída para Outro Estado - Código Enquadramento Legal = 4',
            'Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0',
            'ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência',
            'Quantidade',  'Valor Unitário do Saldo', 'Valor Total do Saldo', 'Valor do Ressarcimento', 'Valor do Complemento',
            'ICMS Efetivo da Entrada', 'ICMS - Crédito da Operação Própria (artigo 271 do RICMS)']

ficha_3_revizia = pd.DataFrame(columns=colunas)
teste = ler_arquivo_para_dataframe(bucket_name=bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
                                  file_type='xlsx')

Erro ao ler arquivo do S3: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

In [114]:
teste['VLR_RESSARCIMENTO'].sum()

np.float64(1177275.8649994466)

In [115]:
ficha_3_revizia['Código da Mercadoria'] = teste['COD_ITEM']
ficha_3_revizia['Número da Ordem'] = teste.groupby('COD_ITEM').cumcount() + 1
ficha_3_revizia['Data'] = teste['DATA']
ficha_3_revizia['Chave'] = teste['CHV_DOC']
ficha_3_revizia['Tipo'] = teste['IND_OPER']
ficha_3_revizia['Código do Remetente ou Destinatário'] = teste['CHV_DOC'].str.slice(6, 20)
ficha_3_revizia['CFOP'] = teste['CFOP']
ficha_3_revizia['Série do documento'] = ficha_3_revizia['Chave'].str.slice(22, 25)
ficha_3_revizia['Número da nota'] = ficha_3_revizia['Chave'].str.slice(25,34)
ficha_3_revizia['Número do Item no Documento XML'] = teste['NUM_ITEM']
ficha_3_revizia['Quantidade (Entrada)'] = np.where(teste['IND_OPER'] == 0, teste['QTD_CAT'], np.nan)
ficha_3_revizia['Valor Total do ICMS Suportado na Retenção ou Antecipação por ST'] = teste['ICMS_TOT']
ficha_3_revizia['Quantidade (Saída)'] = np.where(teste['IND_OPER'] == 1, teste['QTD_CAT'], np.nan)
ficha_3_revizia['Valor Unitário do ICMS Suportado'] = teste['ICMS_SAIDA_UNI']
ficha_3_revizia['Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1'] = np.where(teste['COD_LEGAL'] == 1,
                                                                                                   teste['ICMS_SAIDA'],
                                                                                                   np.nan)
ficha_3_revizia['Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0'] = np.where(teste['COD_LEGAL'] == 0,
                                                                                                                     teste['ICMS_SAIDA'],
                                                                                                                     np.nan)
ficha_3_revizia['Fato Gerador Não Realizado - Código Enquadramento Legal = 2'] = np.where(teste['COD_LEGAL'] == 2,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3'] = np.where(teste['COD_LEGAL'] == 3,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['Saída para Outro Estado - Código Enquadramento Legal = 4'] = np.where(teste['COD_LEGAL'] == 4,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência'] = teste['VLR_CONF_0']
ficha_3_revizia['Quantidade'] = teste['QTD_SALDO']
ficha_3_revizia['Valor Total do Saldo']  = teste['ICMS_TOT_SALDO']
ficha_3_revizia['Valor Unitário do Saldo'] = ficha_3_revizia['Valor Total do Saldo'] / ficha_3_revizia['Quantidade']
ficha_3_revizia['Valor do Ressarcimento'] = teste['VLR_RESSARCIMENTO']
ficha_3_revizia['Valor do Complemento'] = teste['VLR_COMPLEMENTO']
ficha_3_revizia['ICMS Efetivo da Entrada'] = np.where(teste['COD_LEGAL'].isin([2, 3, 4]), 
                                                      teste['ICMS_EFETIVO_ENTRADA'],
                                                      np.nan)
ficha_3_revizia['ICMS - Crédito da Operação Própria (artigo 271 do RICMS)'] = np.where(teste['COD_LEGAL'] == 4,
                                                                                       teste['ICMS_EFETIVO_ENTRADA'],
                                                                                       np.nan)

# Função para extrair os dados de acordo com o modelo da chave
def extrair_dados(chave):
    if isinstance(chave, str) and len(chave) == 44:  # Verifica se a chave tem 44 caracteres
        modelo = chave[20:22]  # Posições 21 e 22 determinam o modelo

        if modelo == "55":  # Modelo 55 (NF-e)
            serie = chave[22:25]  # Posições 23 a 25 (3 caracteres)
            numero_nota = chave[25:34]  # Posições 26 a 34 (9 caracteres)
        elif modelo == "59":  # Modelo 59 (CFe-SAT)
            serie = chave[22:31]  # Posições 23 a 31 (9 caracteres - Número de Série do SAT)
            numero_nota = chave[31:37]  # Posições 32 a 37 (6 caracteres - Número do CFe-SAT)
        else:
            serie, numero_nota = None, None  # Caso seja um modelo diferente

        return serie, numero_nota
    return None, None


# Aplicar a função em todas as chaves e preencher as colunas
ficha_3_revizia[['Série do documento', 'Número da nota']] = ficha_3_revizia['Chave'].apply(lambda x: pd.Series(extrair_dados(x)))

# Função para inserir a linha "cabeçalho" antes das linhas do grupo
def inserir_linha_inicial(grupo):
    # Identificar o código da mercadoria (COD_ITEM) do grupo atual
    cod_item = grupo['Código da Mercadoria'].iloc[0]
    
    # Buscar a primeira linha correspondente no 'teste'
    # (assumindo que todo cod_item de ficha_3_revizia está presente em teste)
    row_teste = teste.loc[teste['COD_ITEM'] == cod_item].iloc[0]

    # Montar o dicionário da nova linha, com colunas específicas
    nova_linha = {
        'Código da Mercadoria': cod_item,
        'Quantidade': row_teste['QTD_INI'],
        'Valor Unitário do Saldo': row_teste['ULT_ICMS_SAIDA_UNI'],
        'Valor Total do Saldo': row_teste['ICMS_INI'],
        # Se quiser deixar as demais colunas em branco (NaN) ou algum valor fixo
        # 'Outra Coluna': '',
        # ...
    }
    
    # Converter a nova linha em um DataFrame de uma única linha
    nova_linha_df = pd.DataFrame([nova_linha])
    
    # Concatenar a nova linha ao grupo (colocando a nova linha antes)
    return pd.concat([nova_linha_df, grupo], ignore_index=True)

# Agrupar por 'Código da Mercadoria' e aplicar a função
ficha_3_revizia_com_cabecalho = (
    ficha_3_revizia
    .groupby('Código da Mercadoria', group_keys=False)
    .apply(inserir_linha_inicial)
)

ficha_3_revizia_com_cabecalho = ficha_3_revizia_com_cabecalho[['Código da Mercadoria', 'Número da Ordem', 'Data', 'Chave', 'Tipo', 'Série do documento', 'Número da nota',
            'Código do Remetente ou Destinatário', 'CFOP', 'Número do Item no Documento XML', 'Quantidade (Entrada)',
            'Valor Total do ICMS Suportado na Retenção ou Antecipação por ST', 'Quantidade (Saída)',
            'Valor Unitário do ICMS Suportado', 'Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1',
            'Fato Gerador Não Realizado - Código Enquadramento Legal = 2', 
            'Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3',
            'Saída para Outro Estado - Código Enquadramento Legal = 4',
            'Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0',
            'ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência',
            'Quantidade',  'Valor Unitário do Saldo', 'Valor Total do Saldo', 'Valor do Ressarcimento', 'Valor do Complemento',
            'ICMS Efetivo da Entrada', 'ICMS - Crédito da Operação Própria (artigo 271 do RICMS)']]


ficha_3_revizia_com_cabecalho

C:\Users\vinic\AppData\Local\Temp\ipykernel_2116\1347571090.py:94: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(inserir_linha_inicial)

,Código da Mercadoria,Número da Ordem,Data,Chave,Tipo,Série do documento,Número da nota,Código do Remetente ou Destinatário,CFOP,Número do Item no Documento XML,Quantidade (Entrada),Valor Total do ICMS Suportado na Retenção ou Antecipação por ST,Quantidade (Saída),Valor Unitário do ICMS Suportado,Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1,Fato Gerador Não Realizado - Código Enquadramento Legal = 2,Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3,Saída para Outro Estado - Código Enquadramento Legal = 4,Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0,ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência,Quantidade,Valor Unitário do Saldo,Valor Total do Saldo,Valor do Ressarcimento,Valor do Complemento,ICMS Efetivo da Entrada,ICMS - Crédito da Operação Própria (artigo 271 do RICMS)
0,001010101002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.83,1.249722,167.250357,NaN,NaN,NaN,NaN
1,001010101002,1.0,2020-03-16,35200365369985000504550060000473171100175734,1.0,006,000047317,65369985000504,5405.0,3.0,NaN,NaN,8.0,1.249722,NaN,NaN,NaN,NaN,9.997780,17.1216,125.83,1.249722,157.252577,0.0,7.123820,NaN,NaN
2,001010101002,2.0,2020-03-18,35200365369985000504550060000473911100009840,1.0,006,000047391,65369985000504,5405.0,1.0,NaN,NaN,3.0,1.249722,NaN,NaN,NaN,NaN,3.749167,8.1432,122.83,1.249722,153.503410,0.0,4.394033,NaN,NaN
3,001010101002,3.0,2020-04-24,35200465369985000504550060000483591100304419,1.0,006,000048359,65369985000504,5405.0,8.0,NaN,NaN,50.0,1.249722,NaN,NaN,NaN,NaN,62.486123,135.7200,72.83,1.249722,91.017287,0.0,73.233877,NaN,NaN
4,001010101002,4.0,2020-05-06,35200565369985000504550060000486951100123356,1.0,006,000048695,65369985000504,5405.0,19.0,NaN,NaN,10.0,1.249722,NaN,NaN,NaN,NaN,12.497225,32.5800,62.83,1.249722,78.520062,0.0,20.082775,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,VIAVE3001005,3.0,2020-10-23,35201065369985000504590003340440078578021018,1.0,000334044,007857,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.402332,NaN,NaN,NaN,NaN,0.402332,1.6788,1.00,0.402332,0.402332,0.0,0.000000,NaN,NaN
4,VIAVE3001005,4.0,2020-10-23,35201065369985000504590003340440078578021018,1.0,000334044,007857,65369985000504,5102.0,2.0,NaN,NaN,1.0,0.402332,NaN,NaN,NaN,NaN,0.402332,1.6788,0.00,NaN,0.000000,0.0,0.000000,NaN,NaN
0,VIAVE3001006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.201022,0.402044,NaN,NaN,NaN,NaN
1,VIAVE3001006,1.0,2020-06-18,35200665369985000504590003340440044091519950,1.0,000334044,004409,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.201022,NaN,NaN,NaN,NaN,0.201022,0.8388,1.00,0.201022,0.201022,0.0,0.000000,NaN,NaN
2,VIAVE3001006,2.0,2020-06-26,35200665369985000504590003340440046248265500,1.0,000334044,004624,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.201022,NaN,NaN,NaN,NaN,0.201022,0.8388,0.00,NaN,0.000000,0.0,0.000000,NaN,NaN

In [116]:
salvar_dataframe_no_s3(ficha_3_revizia_com_cabecalho,
                    bucket_name,
                    f'Cat42/{nome_empresa.title()}/Ficha 3 Revizia/ficha_3_modelo_revizia_{nome_empresa.title()}_{cnpj}.xlsx',
                                                           file_type='xlsx')

Arquivo salvo com sucesso em 'Cat42/Tateti/Ficha 3 Revizia/ficha_3_modelo_revizia_Tateti_65369985000504.xlsx'.

In [6]:
sum(teste['VLR_RESSARCIMENTO'])

2700214.5340872207

In [ ]:
import pandas as pd

# Caminho do arquivo Excel
caminho_arquivo = r"C:\Users\simas\OneDrive\Área de Trabalho\teste.xlsx"

# Carregar a planilha
df = pd.read_excel(caminho_arquivo, dtype=str)


# Função para extrair os dados de acordo com o modelo da chave
def extrair_dados(chave):
    if isinstance(chave, str) and len(chave) == 44:  # Verifica se a chave tem 44 caracteres
        modelo = chave[20:22]  # Posições 21 e 22 determinam o modelo

        if modelo == "55":  # Modelo 55 (NF-e)
            serie = chave[22:25]  # Posições 23 a 25 (3 caracteres)
            numero_nota = chave[25:34]  # Posições 26 a 34 (9 caracteres)
        elif modelo == "59":  # Modelo 59 (CFe-SAT)
            serie = chave[22:31]  # Posições 23 a 31 (9 caracteres - Número de Série do SAT)
            numero_nota = chave[31:37]  # Posições 32 a 37 (6 caracteres - Número do CFe-SAT)
        else:
            serie, numero_nota = None, None  # Caso seja um modelo diferente

        return serie, numero_nota
    return None, None


# Aplicar a função em todas as chaves e preencher as colunas
df[['Série do documento', 'Número da nota']] = df['Chave'].apply(lambda x: pd.Series(extrair_dados(x)))

# Salvar a planilha atualizada
caminho_saida = r"C:\Users\simas\OneDrive\Área de Trabalho\teste_atualizado.xlsx"
df.to_excel(caminho_saida, index=False)

print(f"Arquivo atualizado salvo em: {caminho_saida}")

In [ ]:
# tabela_2 = tabela_2.drop('Unnamed: 0', axis=1)
    tabela_2 = tabela_2[tabela_2.groupby('COD_ITEM')['IND_OPER'].transform(lambda x: not (x.nunique() == 1 and x.iloc[0] == 0))]
    tabela_2 = tabela_2.sort_values(by=['COD_ITEM', 'DATA', 'IND_OPER', 'SUB_TIPO'], 
                                ascending=[True, True, True, True]).reset_index().drop('index', axis=1)

    tabela_2['QTD_CAT'] = tabela_2['QTD_CAT'].astype(float)

    ficha_3 = tabela_2[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'IND_OPER', 'SUB_TIPO', 'QTD_CAT', 'Valor ICMS Operação',
                            'CST', 'ALIQUOTA', 'FONTE']]

    query = 'SELECT * FROM produtos'
    produtos = pd.read_sql_query(query, connection)

    # Ordenação da tabela de acordo com os critérios definidos
    ficha_3['DATA'] = pd.to_datetime(ficha_3['DATA'], format='%Y-%m-%d')
    ficha_3 = ficha_3.sort_values(by=['COD_ITEM', 'DATA', 'IND_OPER', 'SUB_TIPO'], 
                                ascending=[True, True, True, True])

    ficha_3['ICMS_TOT'] = tabela_2['ICMS_TOT'].astype(float)
    ficha_3['ICMS_TOT_SAIDA'] = tabela_2['ICMS_TOT_SAIDA'].astype(float)

    ficha_3['VALOR'] = tabela_2['VALOR']

    ficha_3 = ficha_3.merge(produtos[['codigo_produto', 'mva_antes']], 
                        left_on='COD_ITEM',
                        right_on='codigo_produto',
                        how='left')
    ficha_3 = ficha_3.drop('codigo_produto', axis=1).rename(columns={'mva_antes': 'MVA'})

    ficha_3['VALOR'] = ficha_3['VALOR'].astype(str).replace('-', np.nan).astype(float)
    ficha_3['ALIQUOTA'] = ficha_3['ALIQUOTA'].astype(str).replace('-', np.nan).astype(float)
    ficha_3['MVA'] = ficha_3['MVA'].astype(str).replace('-', np.nan).replace('None', np.nan).astype(float)

    cond_1 = ((ficha_3['CST'].astype(float) == 60) & ((ficha_3['ICMS_TOT'] == 0) | (ficha_3['ICMS_TOT'].isnull())))
    cond_2 = ((ficha_3['CFOP'].isin([1403, 1409, 1411, 1949, 2403, 2411, 1202, 2202])) & ((ficha_3['ICMS_TOT'] == 0) | (ficha_3['ICMS_TOT'].isnull())))

    ficha_3['ICMS_TOT'] = np.where(cond_1 | cond_2 , 
                                (ficha_3['VALOR'] * (ficha_3['ALIQUOTA'] / 100)) * (ficha_3['MVA'] + 1),
                                ficha_3['ICMS_TOT'])

    ficha_3['ICMS_TOT'] = np.where((ficha_3['CFOP'].astype(float).isin([1102, 2102])) | (ficha_3['IND_OPER'] == 1),
                                    np.nan,
                                    ficha_3['ICMS_TOT'])
    
    # ficha_3['ICMS_TOT_SAIDA'] = np.where((ficha_3['IND_OPER'] == 1) & (),
    #                                      (ficha_3['VALOR'] * (ficha_3['ALIQUOTA'] / 100)) * (ficha_3['MVA'] + 1),
    #                                      np.nan)

    cond_1 = ((ficha_3['CST'].astype(float) == 60) & ((ficha_3['Valor ICMS Operação'] == 0) | (ficha_3['Valor ICMS Operação'].isnull())))
    cond_2 = ((ficha_3['CFOP'].isin([1403, 1409, 1411, 1949, 2403, 2411])) & ((ficha_3['Valor ICMS Operação'] == 0) | (ficha_3['Valor ICMS Operação'].isnull())))

    ficha_3['Valor ICMS Operação'] = np.where(cond_1 | cond_2,
                                            (ficha_3['ALIQUOTA'].astype(float)/ 100) * ficha_3['VALOR'].astype(float),
                                            ficha_3['Valor ICMS Operação'])

    ficha_3['Valor ICMS Operação'] = np.where((ficha_3['CFOP'].astype(float).isin([1102, 2102])) | ((ficha_3['CFOP'].astype(float).isin([1202, 2202])) & (ficha_3['CST'] != 60)),
                                    np.nan,
                                    ficha_3['Valor ICMS Operação'])

    data = ficha_3[['COD_ITEM', 'DATA', 'QTD_CAT', 'IND_OPER', 'CFOP']]
    
    # Transformação da coluna 'DATA' para o tipo correto
    data['DATA'] = pd.to_datetime(data['DATA'], format='%Y-%m-%d')

    # Ordenação do dataset para cálculo correto do ICMS inicial

    data['IND_OPER'] = data['IND_OPER'].astype(int)
    data = data.sort_values(by=['COD_ITEM','DATA', 'IND_OPER'], ascending=[True, True, True])

    # Cáculo dos saldos das operações para definição da Quantidade Inicial
    data['OPER'] = np.where(data['IND_OPER'] == 0, data['QTD_CAT'], -data['QTD_CAT'])
    data['SALDO'] = data.groupby('COD_ITEM')['OPER'].cumsum()

    # Criação da coluna para as informações da Quantidade Inicial

    min_saldo = data.groupby('COD_ITEM')['SALDO'].transform('min')

    # Set 'QTD_INI' to the minimum 'SALDO' value if it's less than or equal to 0,
    # otherwise set it to 0
    data['QTD_INI'] = np.where(min_saldo <= 0, min_saldo.abs(), 0)

    # Get the first rows within each group
    first_rows = data.groupby('COD_ITEM').head(1)

    # Set 'QTD_INI' to NaN for all rows except the last rows within each group
    data['QTD_INI'] = np.where(data.index.isin(first_rows.index), data['QTD_INI'], np.nan)

    # Update 'QTD_INI' with calculated values for the last rows
    data.loc[first_rows.index, 'QTD_INI'] = first_rows['QTD_INI']

    # Cálculo do ICMS inicial 

    data['SUB_TIPO'] = tabela_2['SUB_TIPO']
    data['ICMS_TOT_0'] = ficha_3['ICMS_TOT']
    data['CST'] = ficha_3['CST']
    data['Valor ICMS Operação'] = ficha_3['Valor ICMS Operação'].astype(float)
    data['VALOR_UNIT'] = np.where(data['IND_OPER'] == 0,
                                data['ICMS_TOT_0'].fillna(0) / data['QTD_CAT'],
                                np.nan)
    data['VALOR_OP_UNIT'] = np.where(data['IND_OPER'] == 0,
                                    data['Valor ICMS Operação'].fillna(0) / data['QTD_CAT'],
                                    np.nan)

    data['ICMS_INI'] = None
    data['ICMS_OP_INI'] = None

    # Iterar sobre cada valor único de 'COD_ITEM'
    for cod in data['COD_ITEM'].unique():
        # Filtrar todas as linhas para o 'COD_ITEM' atual
        df_cod = data[data['COD_ITEM'] == cod]
        
        # Identificar a primeira linha dentre todas do 'COD_ITEM'
        idx_first = df_cod.index[0]

        # Identificar a primeira linha onde 'IND_OPER' == 0
        df_ind_oper_0 = df_cod[df_cod['IND_OPER'] == 0]
        if not df_ind_oper_0.empty:
            idx_oper_0 = df_ind_oper_0.index[0]

            # Fazer os cálculos e salvar os valores na primeira linha do 'COD_ITEM'
            data.at[idx_first, 'ICMS_INI'] = data.at[idx_oper_0, 'VALOR_UNIT'] * data.at[idx_first, 'QTD_INI']
            data.at[idx_first, 'ICMS_OP_INI'] = data.at[idx_oper_0, 'VALOR_OP_UNIT'] * data.at[idx_first, 'QTD_INI']

    produtos_somente_saida = tabela_2.groupby('COD_ITEM')['IND_OPER'].all()
    produtos_somente_saida = produtos_somente_saida[produtos_somente_saida == True].index
    prods_icms_0 = data.drop_duplicates(subset='COD_ITEM', keep='first')[(data['QTD_INI'] != 0) & (((data['ICMS_INI'] == 0) | (data['ICMS_INI'].isnull())) | ((data['ICMS_OP_INI'] == 0) | (data['ICMS_OP_INI'].isnull())))]
    prods_icms_ini_igual_op = data.drop_duplicates(subset='COD_ITEM', keep='first')[data['ICMS_INI'] == data['ICMS_OP_INI']]
    for produto in list(produtos_somente_saida) + list(prods_icms_0['COD_ITEM'].unique()) + list(prods_icms_ini_igual_op['COD_ITEM'].unique()):
    # for produto in data['COD_ITEM'].unique():
    # Executa a consulta para obter os valores mva_antes e mva_depois
        query = f"SELECT mva_antes, mva_depois FROM produtos WHERE codigo_produto = '{produto}'"
        try:
            mva = float(pd.read_sql_query(query, connection).dropna(axis=1).iloc[0,0])
        except:
            mva = 0
        # print('MVA: ', mva)
        # Calcula o lucro e a quantidade total
        lucro = sum(ficha_3[(ficha_3['COD_ITEM'] == produto) & (ficha_3['IND_OPER'] == 1)]['ICMS_TOT_SAIDA'])
        tot_qtde = sum(ficha_3[(ficha_3['COD_ITEM'] == produto) & (ficha_3['IND_OPER'] == 1)]['QTD_CAT'])
        aliquota = ficha_3[ficha_3['COD_ITEM'] == produto]['ALIQUOTA'].values[0] / 100

        
        try:
            # Calcula o valor unitário, base ST estimada e ICMS
            valor_unit = (lucro * 0.8) / tot_qtde
            # print('Valor unitario: ', valor_unit)
            base_st_estimada = valor_unit + (valor_unit * mva)
            # print('Base estimada: ', base_st_estimada)
            icms_op_unit = valor_unit * aliquota
            icms_suport_unit = base_st_estimada * aliquota
            # print('Icms suportado unitario: ', icms_suport_unit)
            icms_inicial = icms_suport_unit * tot_qtde
            # print('ICMS Inicial: ', icms_inicial)

        except:
            icms_inicial = 0
            icms_op_unit = 0
            

        # Verifica se o produto está presente no DataFrame 'data'
        produto_idx = data[data['COD_ITEM'] == produto].index

        if not produto_idx.empty:
            # Garante que a coluna 'ICMS_INI' seja do tipo float
            data['ICMS_INI'] = data['ICMS_INI'].astype(float)
            data['ICMS_OP_INI'] = data['ICMS_OP_INI'].astype(float)

            # Atualiza o valor na primeira linha correspondente ao COD_ITEM
            data.loc[produto_idx[0], 'ICMS_INI'] = icms_inicial
            data.loc[produto_idx[0], 'ICMS_OP_INI'] = icms_op_unit * data.loc[produto_idx[0], 'QTD_INI']

    # Definição das colunas para cálculo de ressarcimento de acordo com as regras
    ficha_3['QTD_INI'] = data['QTD_INI'].astype(float)
    ficha_3['ICMS_INI'] = data['ICMS_INI'].astype(float)
    ficha_3['ICMS_OP_INI'] = data['ICMS_OP_INI'].astype(float)
    ficha_3['ICMS_INI'] = np.where((ficha_3['QTD_INI'] == 0) | (ficha_3['ICMS_INI'].isnull() & ficha_3['QTD_INI'].notnull()),
                                    0,
                                    ficha_3['ICMS_INI'])

    ficha_3 = ficha_3[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'IND_OPER', 
                        'SUB_TIPO', 'QTD_CAT', 'Valor ICMS Operação','CST', 'QTD_INI','ICMS_INI', 'ICMS_OP_INI',
                        'ALIQUOTA', 'FONTE', 'ICMS_TOT','ICMS_TOT_SAIDA', 'VALOR']]

    # Inicializa as colunas
    ficha_3['valor_op_fixo'] = 0
    ficha_3['qtd_fixa'] = 0

    # Processamento dos valores fixos acumulados
    for cod in ficha_3['COD_ITEM'].unique():
        subset = ficha_3[ficha_3['COD_ITEM'] == cod].copy()

        acum_val = 0
        acum_qtd = 0

        for i, row in subset.iterrows():
            if row['IND_OPER'] == 0:
                ficha_3.loc[i, 'valor_op_fixo'] = acum_val
                ficha_3.loc[i, 'qtd_fixa'] = acum_qtd

                if pd.isna(row['Valor ICMS Operação']):
                    acum_val += 0
                else:
                    acum_val += row['Valor ICMS Operação']
                acum_qtd += row['QTD_CAT']

    # Cálculo do valor médio
    valor_medio = []

    for cod in ficha_3['COD_ITEM'].unique():
        subset = ficha_3[ficha_3['COD_ITEM'] == cod].copy().reset_index()

        for i, row in subset.iterrows():
            if i == 0:  # Primeira linha
                if row['IND_OPER'] == 0:
                    # Calcular com valores acumulados
                    if pd.isna(row['Valor ICMS Operação']):
                        num = row['valor_op_fixo'] + 0 + row['ICMS_OP_INI']
                    else:
                        num = row['valor_op_fixo'] + row['Valor ICMS Operação'] + row['ICMS_OP_INI']
                    den = row['qtd_fixa'] + row['QTD_CAT'] + row['QTD_INI']
                    valor_medio.append(num / den)
                elif row['IND_OPER'] == 1:
                    # Calcular com ICMS_OP_INI e QTD_INI
                    num = row['ICMS_OP_INI']
                    den = row['QTD_INI']
                    valor_medio.append(num / den)
            else:  # Demais linhas
                if row['IND_OPER'] == 0:
                    # Calcular com valores acumulados
                    if pd.isna(row['Valor ICMS Operação']):
                        num = row['valor_op_fixo'] + 0 + row['ICMS_OP_INI']
                    else:
                        num = row['valor_op_fixo'] + row['Valor ICMS Operação'] + row['ICMS_OP_INI']
                    den = row['qtd_fixa'] + row['QTD_CAT'] + subset.iloc[0]['QTD_INI']
                    valor_medio.append(num / den)
                elif row['IND_OPER'] == 1:
                    # Para IND_OPER == 1, deixamos como NaN
                    valor_medio.append(np.nan)

    # Adiciona a coluna 'valor_medio' ao DataFrame e preenche valores ausentes
    ficha_3['valor_medio'] = valor_medio
    ficha_3['valor_medio'] = ficha_3['valor_medio'].ffill()

    # Cálculos finais
    ficha_3['COD_LEGAL'] = tabela_2['COD_LEGAL'].astype(float)
    ficha_3['ICMS_EFETIVO_ENTRADA'] = ficha_3['valor_medio'] * ficha_3['QTD_CAT']
    ficha_3['ICMS_EFETIVO_ENTRADA'] = np.where(ficha_3['COD_LEGAL'] > 1,
                                            ficha_3['ICMS_EFETIVO_ENTRADA'],
                                            np.nan)

    ficha_3['IND_OPER'] = ficha_3['IND_OPER'].astype(int)
    ficha_3['SUB_TIPO'] = ficha_3['SUB_TIPO'].astype(int)

    mask_condition1 = (ficha_3['IND_OPER'] == 0) & (ficha_3['SUB_TIPO'] == 1)
    mask_condition2 = (ficha_3['IND_OPER'] != 0) & (ficha_3['SUB_TIPO'] == -1)

    qtd_ent1_devolv_ent = list(np.where(mask_condition1, ficha_3['QTD_CAT'], 0) + np.where(mask_condition2, -ficha_3['QTD_CAT'], 0))
    ficha_3['QTD_ent1_devolv_ent'] = qtd_ent1_devolv_ent
    
    mask = ficha_3['QTD_ent1_devolv_ent'] > 0

    ficha_3['ICMS_TOT_ent_unit'] = np.where(mask, ficha_3['ICMS_TOT'].fillna(0) / ficha_3['QTD_ent1_devolv_ent'], 0)
    
    ficha_3['ULT_ICMS_TOT_ent_unit'] = np.nan

    values = np.where(
        (ficha_3['QTD_INI'] != 0) & 
        (ficha_3['COD_ITEM'] == ficha_3['COD_ITEM'].shift()) & 
        (ficha_3['QTD_ent1_devolv_ent'].shift() > 0),
        ficha_3['ICMS_TOT_ent_unit'].shift(),
        np.where(
            (ficha_3['QTD_INI'] == 0),
            0.01,
            ficha_3['ICMS_INI'] / ficha_3['QTD_INI']
        )
    )
    
    
    ficha_3['ULT_ICMS_TOT_ent_unit'] = values

    ficha_3['ULT_ICMS_TOT_ent_unit'] = ficha_3['ULT_ICMS_TOT_ent_unit'].ffill()
    
    mask_condition1 = (ficha_3['IND_OPER'] == 1) & (ficha_3['SUB_TIPO'] == 1)
    mask_condition2 = (ficha_3['IND_OPER'] != 1) & (ficha_3['SUB_TIPO'] == -1)

    qtd_saida_1_devolv_saida_t = np.where(mask_condition1, ficha_3['QTD_CAT'], 0) + np.where(mask_condition2, -ficha_3['QTD_CAT'], 0)

    ficha_3['qtd_saida_1_devolv_saida'] = qtd_saida_1_devolv_saida_t
    
    ficha_3['QTD_SALDO'] = ficha_3.groupby('COD_ITEM').apply(lambda x: (
    x['QTD_INI'].iloc[0] + (x['QTD_ent1_devolv_ent'] - x['qtd_saida_1_devolv_saida']).cumsum())).reset_index(level=0, drop=True)
    
    ficha_3['QTD_SALDO'] = np.where((ficha_3['QTD_SALDO'] < 0.01) & (ficha_3['QTD_SALDO'] > -0.01),
                                         0,
                                         ficha_3['QTD_SALDO'])      
    
    ficha_3['DATA'] = ficha_3['DATA'].astype(str)
    ficha_3['REF'] = ficha_3['DATA']
    ficha_3['REF'] = [datetime.strptime(x, '%Y-%m-%d').strftime('%m-%Y') for x in ficha_3['REF']]

    # Definição do primeiro valor de ICMS_SAIDA_UNI
    icms_saida_uni = [] 

    # Definição do primeiro valor de ULT_ICMS_SAIDA_UNI
    ult_icms_saida_uni = [] 

    # Definição do primeiro valor de ICMS_SAIDA
    icms_saida = [] 

    # Definição do primeiro valor de ICMS_TOT_SALDO
    icms_tot_saldo = [] 

    # Definição do primeiro valor de ICMS_TOT_1
    icms_tot_1 = []

    # Definição de todos os outros valores para cada campo acima
    for code in ficha_3['COD_ITEM'].unique():

        icms_saida_uni_int = []
        ult_icms_saida_uni_int = []
        icms_saida_int = []
        icms_tot_saldo_int = []
        icms_tot_1_int = []
        qtd_saida_1_devolv_saida = list(ficha_3[ficha_3['COD_ITEM'] == code]['qtd_saida_1_devolv_saida'])
        qtd_saldo = list(ficha_3[ficha_3['COD_ITEM'] == code]['QTD_SALDO'])
        qtd_cat = list(ficha_3[ficha_3['COD_ITEM'] == code]['QTD_CAT'])
        ref = list(ficha_3[ficha_3['COD_ITEM'] == code]['REF'])

        for i,row in ficha_3[ficha_3['COD_ITEM']==code].reset_index(drop=True).iterrows():

        # ICMS_SAIDA_UNI

            if i == 0:
                if qtd_saida_1_devolv_saida[0] > 0:
                    if row['QTD_INI'] == 0:
                        icms_saida_uni_int.append(0)
                    else:  
                        icms_saida_uni_int.append(row['ICMS_INI'] / row['QTD_INI'])
                else:
                    icms_saida_uni_int.append(0)

            else:
                if (qtd_saida_1_devolv_saida[i] != 0) and (qtd_saldo[i-1] != 0):  
                    icms_saida_uni_int.append(icms_tot_saldo_int[i-1] / qtd_saldo[i-1])               
                else:      
                    icms_saida_uni_int.append(0)

        # ULT_ICMS_SAIDA_UNI
            if i== 0:
                if row['QTD_INI'] == 0:
                    ult_icms_saida_uni_int.append(0.01)
                else:           
                    ult_icms_saida_uni_int.append(
                        row['ICMS_INI'] / row['QTD_INI'] if row['QTD_INI'] != 0 else float("nan"))
            else:
                if qtd_saida_1_devolv_saida[i-1] > 0:
                    ult_icms_saida_uni_int.append(icms_saida_uni_int[i-1])
                else:
                    ult_icms_saida_uni_int.append(ult_icms_saida_uni_int[i-1])


        # ICMS_SAIDA
            if qtd_saida_1_devolv_saida[i] < 0:
                icms_saida_int.append(qtd_saida_1_devolv_saida[i]*ult_icms_saida_uni_int[i])
            else:
                icms_saida_int.append(icms_saida_uni_int[i]*qtd_saida_1_devolv_saida[i])

        # ICMS_TOT_1
            if i == 0:
                if (row['QTD_ent1_devolv_ent'] < 0) & (row['QTD_CAT'] == row['QTD_INI']) :
                    icms_tot_1_int.append(-row['ICMS_INI'])
                else:
                    if pd.isna(row['ICMS_TOT']):
                        icms_tot_1_int.append(0)
                    else:
                        icms_tot_1_int.append(row['ICMS_TOT']) 
            else:
                if row['QTD_ent1_devolv_ent'] < 0:
                    if (qtd_cat[i] == qtd_saldo[i-1]):
                        icms_tot_1_int.append(-1*icms_tot_saldo_int[i-1])
                    else:
                        icms_tot_1_int.append(max(row['QTD_ent1_devolv_ent'] * row['ULT_ICMS_TOT_ent_unit'], -1*icms_tot_saldo_int[i-1]))
                else:
                    if pd.isna(row['ICMS_TOT']):
                        icms_tot_1_int.append(0)
                    else:
                        icms_tot_1_int.append(row['ICMS_TOT']) 

        # ICMS_TOT_SALDO
            if i == 0:
                icms_tot_saldo_int.append(row['ICMS_INI'] + icms_tot_1_int[i] - icms_saida_int[i])
            else:
                icms_tot_saldo_int.append(icms_tot_saldo_int[i-1] + icms_tot_1_int[i] - icms_saida_int[i])


        icms_saida_uni += icms_saida_uni_int
        ult_icms_saida_uni += ult_icms_saida_uni_int
        icms_saida += icms_saida_int
        icms_tot_saldo += icms_tot_saldo_int
        icms_tot_1 += icms_tot_1_int

    ficha_3['ICMS_SAIDA_UNI'] = icms_saida_uni
    ficha_3['ULT_ICMS_SAIDA_UNI'] = ult_icms_saida_uni
    ficha_3['ICMS_SAIDA'] = icms_saida
    ficha_3['ICMS_TOT_SALDO'] = icms_tot_saldo
    ficha_3['ICMS_TOT_SALDO'] = np.where((ficha_3['ICMS_TOT_SALDO'] < 0.01) & (ficha_3['ICMS_TOT_SALDO'] > -0.01),
                                         0,
                                         ficha_3['ICMS_TOT_SALDO'])
    ficha_3['ICMS_TOT_1'] = icms_tot_1
    
    ficha_3['ICMS_TOT_PCAT'] = np.where((ficha_3['qtd_saida_1_devolv_saida'] < 0),
                                     np.abs(ficha_3['ICMS_SAIDA_UNI']),
                                     np.where((ficha_3['QTD_ent1_devolv_ent'] != 0),
                                              np.abs(ficha_3['ICMS_TOT_1']),
                                              np.nan))
    
    ficha_3['ICMS_TOT_PCAT'] = np.where((ficha_3['IND_OPER'] == 1) & (ficha_3['SUB_TIPO'] == 1),
                                        np.nan,
                                        ficha_3['ICMS_TOT_PCAT'])
    
    if ficha_3[ficha_3['ICMS_TOT_PCAT'] < 0].shape[0] > 0:
        mensagem = 'EXISTE ICMS TOT PCAT NEGATIVO. FAVOR CHECAR!!'
        print(mensagem)
    
    ficha_3['VLR_CONF_0'] = tabela_2['VL_CONFR_0'].astype(float)
    
    mask = ficha_3['qtd_saida_1_devolv_saida'] > 0
    vlr_confr_unit = np.where(mask, ficha_3['VLR_CONF_0']/ficha_3['qtd_saida_1_devolv_saida'], np.nan)

    ficha_3['VLR_CONFR_UNIT'] = vlr_confr_unit
    
    ult_vlr_confr_unit = [0]
    for i in range(1, ficha_3.shape[0]):
        if ficha_3.iloc[i]['COD_ITEM'] != ficha_3.iloc[i-1]['COD_ITEM']:
            ult_vlr_confr_unit.append(0)
        else:
            if math.isnan(ficha_3.iloc[i-1]['VLR_CONFR_UNIT']):
                ult_vlr_confr_unit.append(ult_vlr_confr_unit[i-1])
            else:
                ult_vlr_confr_unit.append(ficha_3.iloc[i-1]['VLR_CONFR_UNIT'])

    ficha_3['ULT_VLR_CONFR_UNIT'] = ult_vlr_confr_unit
    
    ficha_3['VLR_CONFR_1'] = np.where(ficha_3['qtd_saida_1_devolv_saida'] > 0,
                                   ficha_3['VLR_CONF_0'].astype(float),
                                   np.where(ficha_3['qtd_saida_1_devolv_saida'] < 0,
                                            ficha_3['ULT_VLR_CONFR_UNIT'] * ficha_3['qtd_saida_1_devolv_saida'],
                                            0))
    
    ficha_3['VLR_CONFR_1'] = np.where(ficha_3['VLR_CONFR_1'] <= 0.01,
                                              0.01,
                                              ficha_3['VLR_CONFR_1'])
                                          
    cond_1 = (ficha_3['IND_OPER'] == 1) & (ficha_3['SUB_TIPO'] == 1)
    cond_2 = ficha_3['CFOP'].astype(float).isin([1411, 2411])                      
    ficha_3['VLR_CONFR_1'] = np.where(cond_1 | cond_2, ficha_3['VLR_CONFR_1'], np.nan)
    
    mask_cod_1 = np.abs(ficha_3['ICMS_SAIDA']) > np.abs(ficha_3['VLR_CONFR_1'])
    mask_cod_3 = ficha_3['VLR_CONFR_1'] < ficha_3['ICMS_EFETIVO_ENTRADA']
    apenas_movimentacao = [1102, 2102, 2209, 2949, 5101, 5102, 
                            5118, 5152, 5201, 5202, 5210,
                            5401, 5409, 5410, 5411, 5413, 5551, 5556, 5603,
                            5910, 5911, 5916, 5920, 5921, 5922, 5923, 5949, 
                            6101, 6103, 6119, 6202, 6401, 6403, 6411,
                            6556, 6910, 6911, 6922, 6923]

    ficha_3['VLR_RESSARCIMENTO'] = 0

    ficha_3['VLR_RESSARCIMENTO'] = np.where(ficha_3['CFOP'].isin(apenas_movimentacao), 0, ficha_3['VLR_RESSARCIMENTO'])

    ficha_3['VLR_RESSARCIMENTO'] = np.where((ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) != 60), 
                                            0, 
                                            ficha_3['VLR_RESSARCIMENTO'])

    ficha_3['VLR_RESSARCIMENTO'] = np.where((ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) == 60) & mask_cod_1,
                                            ficha_3['ICMS_SAIDA'] - ficha_3['VLR_CONFR_1'], 
                                            ficha_3['VLR_RESSARCIMENTO'])

    ficha_3['VLR_RESSARCIMENTO'] = np.where((ficha_3['COD_LEGAL'] == 1) & mask_cod_1 & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])),
                                            ficha_3['ICMS_SAIDA'] - ficha_3['VLR_CONFR_1'], 
                                            ficha_3['VLR_RESSARCIMENTO'])

    ficha_3['VLR_RESSARCIMENTO'] = np.where((ficha_3['COD_LEGAL'] == 2) & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])), 
                                            ficha_3['ICMS_EFETIVO_ENTRADA'].fillna(0), 
                                            ficha_3['VLR_RESSARCIMENTO'])

    ficha_3['VLR_RESSARCIMENTO'] = np.where((ficha_3['COD_LEGAL'] == 3) & mask_cod_3 & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])), 
                                            ficha_3['ICMS_EFETIVO_ENTRADA'].fillna(0), 
                                            ficha_3['VLR_RESSARCIMENTO'])

    ficha_3['VLR_RESSARCIMENTO'] = np.where((ficha_3['COD_LEGAL'] == 4) & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])), 
                                            np.abs(ficha_3['ICMS_SAIDA'] - ficha_3['ICMS_EFETIVO_ENTRADA'].fillna(0)), 
                                            ficha_3['VLR_RESSARCIMENTO'])

    # Garantir que o cálculo de 'VLR_RESSARCIMENTO' seja 0 para as condições específicas
    ficha_3['VLR_RESSARCIMENTO'] = np.where(
        (ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) != 60),
        0,
        ficha_3['VLR_RESSARCIMENTO']
    )

    ficha_3['VLR_RESSARCIMENTO'] = np.where(ficha_3['CFOP'].isin([1411, 2411]),
                                            0,
                                            ficha_3['VLR_RESSARCIMENTO'])

    mask_cod_1 = np.abs(ficha_3['ICMS_SAIDA']) < np.abs(ficha_3['VLR_CONFR_1'])
    mask_cod_3 = ficha_3['VLR_CONFR_1'] > ficha_3['ICMS_EFETIVO_ENTRADA']

    ficha_3['VLR_COMPLEMENTO'] = 0

    ficha_3['VLR_COMPLEMENTO'] = np.where(ficha_3['CFOP'].isin(apenas_movimentacao), 
                                        0, 
                                        ficha_3['VLR_COMPLEMENTO'])

    ficha_3['VLR_COMPLEMENTO'] = np.where((ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) != 60), 
                                            0, 
                                            ficha_3['VLR_COMPLEMENTO'])

    ficha_3['VLR_COMPLEMENTO'] = np.where((ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) == 60) & mask_cod_1,
                                            -ficha_3['ICMS_SAIDA'] + ficha_3['VLR_CONFR_1'], 
                                            ficha_3['VLR_COMPLEMENTO'])

    ficha_3['VLR_COMPLEMENTO'] = np.where((ficha_3['COD_LEGAL'] == 1) & mask_cod_1 & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])),
                                            -ficha_3['ICMS_SAIDA'] + ficha_3['VLR_CONFR_1'], 
                                            ficha_3['VLR_COMPLEMENTO'])

    ficha_3['VLR_COMPLEMENTO'] = np.where((ficha_3['COD_LEGAL'] == 2) & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])), 
                                            0, 
                                            ficha_3['VLR_COMPLEMENTO'])

    ficha_3['VLR_COMPLEMENTO'] = np.where((ficha_3['COD_LEGAL'] == 3) & mask_cod_3 & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])), 
                                            ficha_3['VLR_CONFR_1'] - ficha_3['ICMS_EFETIVO_ENTRADA'], 
                                            ficha_3['VLR_COMPLEMENTO'])

    ficha_3['VLR_COMPLEMENTO'] = np.where((ficha_3['COD_LEGAL'] == 4) & (~ficha_3['CFOP'].isin(apenas_movimentacao)) & (~ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])), 
                                            0, 
                                            ficha_3['VLR_COMPLEMENTO'])

    # Garantir que o cálculo de 'VLR_COMPLEMENTO' seja 0 para as condições específicas
    ficha_3['VLR_COMPLEMENTO'] = np.where(
        (ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) != 60),
        0,
        ficha_3['VLR_COMPLEMENTO']
    )

    ficha_3['COD_LEGAL'] = np.where((ficha_3['CFOP'].isin(apenas_movimentacao)) | ((ficha_3['CFOP'].isin([2202, 5117, 5120, 5929])) & (ficha_3['CST'].astype(float) != 60)),
                                    0,
                                    ficha_3['COD_LEGAL'])

    ficha_3['COD_LEGAL'] = np.where((ficha_3['COD_LEGAL'] == 1) & (ficha_3['VLR_RESSARCIMENTO'] != 0) & (ficha_3['ALIQUOTA'] != 0), 1, ficha_3['COD_LEGAL'])
    ficha_3['COD_LEGAL'] = np.where(ficha_3['CFOP'].isin([5404, 5403, 5401]), 1, ficha_3['COD_LEGAL'])
    ficha_3['COD_LEGAL'] = np.where(ficha_3['CFOP'].isin([5409]), 0, ficha_3['COD_LEGAL'])
    ficha_3['COD_LEGAL'] = np.where(ficha_3['CFOP'].isin([1403, 1409, 1102, 2102, 2403, 1409, 5411, 6411, 2409, 5202, 6202]), np.nan, ficha_3['COD_LEGAL'])
    # ficha_3['COD_LEGAL'] = np.where(ficha_3['VLR_COMPLEMENTO'] > 0,
    #                                 0,
    #                                 ficha_3['COD_LEGAL'])

    ficha_3['VLR_CONFR_PCAT'] = np.where(ficha_3['COD_LEGAL'].isin([1, 2, 3, 4]), 
                                            np.abs(ficha_3['VLR_CONFR_1']), np.nan)
    
    ficha_3['VLR_CONFR_PCAT'] = np.where(ficha_3['COD_LEGAL'].isin([2, 4]),
                                         ficha_3['ICMS_EFETIVO_ENTRADA'],
                                         ficha_3['VLR_CONFR_PCAT'])

    ficha_3['VLR_CONFR_PCAT'] = np.where((ficha_3['CFOP'].isin(apenas_movimentacao)) | ((ficha_3['CFOP'].astype(int).isin([5117, 5120, 5929])) & (ficha_3['CST'].astype(float) != 60)), 
                                            np.nan, np.abs(ficha_3['VLR_CONFR_PCAT']))

Arquivo 'Cat42/Ladakh/Ficha 3/ficha_3_Ladakh_07318052000150_v2.xlsx' lido com sucesso!

C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ficha_3_icms_tot['NUM_ITEM'] = ficha_3_icms_tot['NUM_ITEM'].astype(str)
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1100_icms_tot['num_item'] = df_1100_icms_tot['num_item'].astype(str)
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1100_icms_tot['Chv_item'] = df_1100_icms_tot['Chv_doc'] + '-' + df_1100_icms_tot['num_item']
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ficha_3_icms_tot['CHV_ITEM'] = ficha_3_icms_tot['CHV_DOC'] + '-' + ficha_3_icms_tot['NUM_ITEM']
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1100_icms_tot['icms_tot'] = df_1100_icms_tot['icms_tot'].str.replace(',', '.').astype(float)

In [114]:
teste = final_df[final_df['Chv_doc'] == '35220142750994000103550010000000091900080107']
teste

,Cod_reg,Chv_doc,data,num_item,ind_oper,cod_prod,cfop,qtd,icms_tot,vlr_confr,cod_legal
9,1100,35220142750994000103550010000000091900080107,30012022,74,0,1025200,1411,"12,000","25,22",NaN,1.0
141,1100,35220142750994000103550010000000091900080107,30012022,32,0,11025,1411,"27,000","32,83",NaN,1.0
159,1100,35220142750994000103550010000000091900080107,30012022,23,0,11026,1411,"20,000","32,83",NaN,1.0
180,1100,35220142750994000103550010000000091900080107,30012022,29,0,11027,1411,"20,000","32,83",NaN,1.0
203,1100,35220142750994000103550010000000091900080107,30012022,22,0,11028,1411,"19,000","32,83",NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2729,1100,35220142750994000103550010000000091900080107,30012022,126,0,91019,1411,"42,000","0,00",NaN,1.0
2803,1100,35220142750994000103550010000000091900080107,30012022,77,0,922600,1411,"28,000","29,54",NaN,1.0
2813,1100,35220142750994000103550010000000091900080107,30012022,82,0,956001,1411,"18,000","21,94",NaN,1.0
2814,1100,35220142750994000103550010000000091900080107,30012022,81,0,956002,1411,"37,000","0,00",NaN,1.0
2815,1100,35220142750994000103550010000000091900080107,30012022,80,0,956003,1411,"48,000","0,00",NaN,1.0

In [120]:
final_df['cfop'] = final_df['cfop'].astype(str)
final_df['cod_legal'] = final_df['cod_legal'].astype(float)

In [126]:
teste[(teste['cfop'].isin(['5405', '1411', '5409', '5403', '5401'])) & (final_df['cod_legal'] >= 1) & (final_df['vlr_confr'].isnull())]

C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\2231388995.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  teste[(teste['cfop'].isin(['5405', '1411', '5409', '5403', '5401'])) & (final_df['cod_legal'] >= 1) & (final_df['vlr_confr'].isnull())]

,Cod_reg,Chv_doc,data,num_item,ind_oper,cod_prod,cfop,qtd,icms_tot,vlr_confr,cod_legal
9,1100,35220142750994000103550010000000091900080107,30012022,74,0,1025200,1411,"12,000","25,22",NaN,1.0
141,1100,35220142750994000103550010000000091900080107,30012022,32,0,11025,1411,"27,000","32,83",NaN,1.0
159,1100,35220142750994000103550010000000091900080107,30012022,23,0,11026,1411,"20,000","32,83",NaN,1.0
180,1100,35220142750994000103550010000000091900080107,30012022,29,0,11027,1411,"20,000","32,83",NaN,1.0
203,1100,35220142750994000103550010000000091900080107,30012022,22,0,11028,1411,"19,000","32,83",NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2729,1100,35220142750994000103550010000000091900080107,30012022,126,0,91019,1411,"42,000","0,00",NaN,1.0
2803,1100,35220142750994000103550010000000091900080107,30012022,77,0,922600,1411,"28,000","29,54",NaN,1.0
2813,1100,35220142750994000103550010000000091900080107,30012022,82,0,956001,1411,"18,000","21,94",NaN,1.0
2814,1100,35220142750994000103550010000000091900080107,30012022,81,0,956002,1411,"37,000","0,00",NaN,1.0
2815,1100,35220142750994000103550010000000091900080107,30012022,80,0,956003,1411,"48,000","0,00",NaN,1.0