In [58]:
# Importação das bibliotecas necessárias
import pandas as pd
import numpy as np
import psycopg2
import math
from datetime import datetime
import sys
import os
import openpyxl
import boto3
from io import BytesIO
from sqlalchemy import create_engine

In [60]:
pd.set_option("display.max_columns", None)

In [62]:
nome_empresa = input("Digite o nome da empresa: ")

if nome_empresa.lower() == 'tateti':
    cnpj = "65369985000504"
    cnpj_produtos = "65369985000334"
    cnpjs = [cnpj]

if nome_empresa.lower() == 'ladakh':
    cnpj = "07318052000150"
    cnpj_produtos = "07318052000150"
    cnpjs = [cnpj]

if nome_empresa.lower() == 'sonda':
    cnpj = "01937635001316"
    cnpj_produtos = "01937635001316"
    cnpjs = [cnpj]

engine = create_engine(
    f"postgresql+psycopg2://cat:5pM2h0MBQu9JHkxHud2A@177.11.49.194:3361/4btaxtech"
)

# Variáveis para acesso ao s3
bucket_name = '4btaxtech'

s3 = boto3.client('s3', 
                  aws_access_key_id='AKIA4RCAOBRSFONXEUTE', 
                  aws_secret_access_key='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',
                  region_name='us-east-1'
                  )

print("✅ Cliente S3 autenticado com sucesso!")

Digite o nome da empresa:  ladakh

✅ Cliente S3 autenticado com sucesso!

In [64]:
def ler_arquivo_para_dataframe(bucket_name, s3_key, file_type='csv', sep=None):
    """
    Lê um arquivo do S3 e carrega em um DataFrame do Pandas.
    
    :param bucket_name: Nome do bucket.
    :param s3_key: Caminho do arquivo no S3.
    :param file_type: Tipo do arquivo ('csv' ou 'xlsx').
    :return: DataFrame do Pandas.
    """
    try:
        response = s3.get_object(Bucket=bucket_name, Key=s3_key)
        if file_type == 'csv':
            df = pd.read_csv(BytesIO(response['Body'].read()), dtype=str, header=0, sep=sep)
        elif file_type == 'xlsx':
            df = pd.read_excel(BytesIO(response['Body'].read()))
        else:
            raise ValueError("Tipo de arquivo não suportado. Use 'csv' ou 'xlsx'.")
        print(f"Arquivo '{s3_key}' lido com sucesso!")
        return df
    except Exception as e:
        print(f"Erro ao ler arquivo do S3: {e}")
        return None
    
def salvar_dataframe_no_s3(df, bucket_name, s3_key, file_type='csv'):
    """
    Salva um DataFrame do Pandas no S3.
    
    :param df: DataFrame a ser salvo.
    :param bucket_name: Nome do bucket.
    :param s3_key: Caminho para salvar o arquivo no S3.
    :param file_type: Tipo do arquivo ('csv' ou 'xlsx').
    """
    try:
        buffer = BytesIO()
        if file_type == 'csv':
            df.to_csv(buffer, index=False, encoding='utf-8')
        elif file_type == 'xlsx':
            with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
                df.to_excel(writer, index=False)
        else:
            raise ValueError("Tipo de arquivo não suportado. Use 'csv' ou 'xlsx'.")
        
        buffer.seek(0)  # Resetar o ponteiro do buffer
        s3.put_object(Bucket=bucket_name, Key=s3_key, Body=buffer.getvalue())
        print(f"Arquivo salvo com sucesso em '{s3_key}'.")
    except Exception as e:
        print(f"Erro ao salvar arquivo no S3: {e}")

In [66]:
def baixar_arquivo(bucket_name, s3_key, local_file_name):
    try:
        s3.download_file(bucket_name, s3_key, local_file_name)
        print(f"Arquivo '{s3_key}' baixado como '{local_file_name}'.")
    except Exception as e:
        print(f"Erro ao baixar arquivo: {e}")

baixar_arquivo(bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
               local_file_name=f'ficha_3_{nome_empresa}_{cnpj}_v2.xlsx')

Erro ao baixar arquivo: An error occurred (404) when calling the HeadObject operation: Not Found

In [67]:
colunas = ['Código da Mercadoria', 'Número da Ordem', 'Data', 'Chave', 'Tipo', 'Série do documento', 'Número da nota',
            'Código do Remetente ou Destinatário', 'CFOP', 'Número do Item no Documento XML', 'Quantidade (Entrada)',
            'Valor Total do ICMS Suportado na Retenção ou Antecipação por ST', 'Quantidade (Saída)',
            'Valor Unitário do ICMS Suportado', 'Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1',
            'Fato Gerador Não Realizado - Código Enquadramento Legal = 2', 
            'Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3',
            'Saída para Outro Estado - Código Enquadramento Legal = 4',
            'Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0',
            'ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência',
            'Quantidade',  'Valor Unitário do Saldo', 'Valor Total do Saldo', 'Valor do Ressarcimento', 'Valor do Complemento',
            'ICMS Efetivo da Entrada', 'ICMS - Crédito da Operação Própria (artigo 271 do RICMS)']

ficha_3_revizia = pd.DataFrame(columns=colunas)
teste = ler_arquivo_para_dataframe(bucket_name=bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
                                  file_type='xlsx')

Erro ao ler arquivo do S3: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

In [114]:
teste['VLR_RESSARCIMENTO'].sum()

np.float64(1177275.8649994466)

In [115]:
ficha_3_revizia['Código da Mercadoria'] = teste['COD_ITEM']
ficha_3_revizia['Número da Ordem'] = teste.groupby('COD_ITEM').cumcount() + 1
ficha_3_revizia['Data'] = teste['DATA']
ficha_3_revizia['Chave'] = teste['CHV_DOC']
ficha_3_revizia['Tipo'] = teste['IND_OPER']
ficha_3_revizia['Código do Remetente ou Destinatário'] = teste['CHV_DOC'].str.slice(6, 20)
ficha_3_revizia['CFOP'] = teste['CFOP']
ficha_3_revizia['Série do documento'] = ficha_3_revizia['Chave'].str.slice(22, 25)
ficha_3_revizia['Número da nota'] = ficha_3_revizia['Chave'].str.slice(25,34)
ficha_3_revizia['Número do Item no Documento XML'] = teste['NUM_ITEM']
ficha_3_revizia['Quantidade (Entrada)'] = np.where(teste['IND_OPER'] == 0, teste['QTD_CAT'], np.nan)
ficha_3_revizia['Valor Total do ICMS Suportado na Retenção ou Antecipação por ST'] = teste['ICMS_TOT']
ficha_3_revizia['Quantidade (Saída)'] = np.where(teste['IND_OPER'] == 1, teste['QTD_CAT'], np.nan)
ficha_3_revizia['Valor Unitário do ICMS Suportado'] = teste['ICMS_SAIDA_UNI']
ficha_3_revizia['Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1'] = np.where(teste['COD_LEGAL'] == 1,
                                                                                                   teste['ICMS_SAIDA'],
                                                                                                   np.nan)
ficha_3_revizia['Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0'] = np.where(teste['COD_LEGAL'] == 0,
                                                                                                                     teste['ICMS_SAIDA'],
                                                                                                                     np.nan)
ficha_3_revizia['Fato Gerador Não Realizado - Código Enquadramento Legal = 2'] = np.where(teste['COD_LEGAL'] == 2,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3'] = np.where(teste['COD_LEGAL'] == 3,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['Saída para Outro Estado - Código Enquadramento Legal = 4'] = np.where(teste['COD_LEGAL'] == 4,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência'] = teste['VLR_CONF_0']
ficha_3_revizia['Quantidade'] = teste['QTD_SALDO']
ficha_3_revizia['Valor Total do Saldo']  = teste['ICMS_TOT_SALDO']
ficha_3_revizia['Valor Unitário do Saldo'] = ficha_3_revizia['Valor Total do Saldo'] / ficha_3_revizia['Quantidade']
ficha_3_revizia['Valor do Ressarcimento'] = teste['VLR_RESSARCIMENTO']
ficha_3_revizia['Valor do Complemento'] = teste['VLR_COMPLEMENTO']
ficha_3_revizia['ICMS Efetivo da Entrada'] = np.where(teste['COD_LEGAL'].isin([2, 3, 4]), 
                                                      teste['ICMS_EFETIVO_ENTRADA'],
                                                      np.nan)
ficha_3_revizia['ICMS - Crédito da Operação Própria (artigo 271 do RICMS)'] = np.where(teste['COD_LEGAL'] == 4,
                                                                                       teste['ICMS_EFETIVO_ENTRADA'],
                                                                                       np.nan)

# Função para extrair os dados de acordo com o modelo da chave
def extrair_dados(chave):
    if isinstance(chave, str) and len(chave) == 44:  # Verifica se a chave tem 44 caracteres
        modelo = chave[20:22]  # Posições 21 e 22 determinam o modelo

        if modelo == "55":  # Modelo 55 (NF-e)
            serie = chave[22:25]  # Posições 23 a 25 (3 caracteres)
            numero_nota = chave[25:34]  # Posições 26 a 34 (9 caracteres)
        elif modelo == "59":  # Modelo 59 (CFe-SAT)
            serie = chave[22:31]  # Posições 23 a 31 (9 caracteres - Número de Série do SAT)
            numero_nota = chave[31:37]  # Posições 32 a 37 (6 caracteres - Número do CFe-SAT)
        else:
            serie, numero_nota = None, None  # Caso seja um modelo diferente

        return serie, numero_nota
    return None, None


# Aplicar a função em todas as chaves e preencher as colunas
ficha_3_revizia[['Série do documento', 'Número da nota']] = ficha_3_revizia['Chave'].apply(lambda x: pd.Series(extrair_dados(x)))

# Função para inserir a linha "cabeçalho" antes das linhas do grupo
def inserir_linha_inicial(grupo):
    # Identificar o código da mercadoria (COD_ITEM) do grupo atual
    cod_item = grupo['Código da Mercadoria'].iloc[0]
    
    # Buscar a primeira linha correspondente no 'teste'
    # (assumindo que todo cod_item de ficha_3_revizia está presente em teste)
    row_teste = teste.loc[teste['COD_ITEM'] == cod_item].iloc[0]

    # Montar o dicionário da nova linha, com colunas específicas
    nova_linha = {
        'Código da Mercadoria': cod_item,
        'Quantidade': row_teste['QTD_INI'],
        'Valor Unitário do Saldo': row_teste['ULT_ICMS_SAIDA_UNI'],
        'Valor Total do Saldo': row_teste['ICMS_INI'],
        # Se quiser deixar as demais colunas em branco (NaN) ou algum valor fixo
        # 'Outra Coluna': '',
        # ...
    }
    
    # Converter a nova linha em um DataFrame de uma única linha
    nova_linha_df = pd.DataFrame([nova_linha])
    
    # Concatenar a nova linha ao grupo (colocando a nova linha antes)
    return pd.concat([nova_linha_df, grupo], ignore_index=True)

# Agrupar por 'Código da Mercadoria' e aplicar a função
ficha_3_revizia_com_cabecalho = (
    ficha_3_revizia
    .groupby('Código da Mercadoria', group_keys=False)
    .apply(inserir_linha_inicial)
)

ficha_3_revizia_com_cabecalho = ficha_3_revizia_com_cabecalho[['Código da Mercadoria', 'Número da Ordem', 'Data', 'Chave', 'Tipo', 'Série do documento', 'Número da nota',
            'Código do Remetente ou Destinatário', 'CFOP', 'Número do Item no Documento XML', 'Quantidade (Entrada)',
            'Valor Total do ICMS Suportado na Retenção ou Antecipação por ST', 'Quantidade (Saída)',
            'Valor Unitário do ICMS Suportado', 'Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1',
            'Fato Gerador Não Realizado - Código Enquadramento Legal = 2', 
            'Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3',
            'Saída para Outro Estado - Código Enquadramento Legal = 4',
            'Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0',
            'ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência',
            'Quantidade',  'Valor Unitário do Saldo', 'Valor Total do Saldo', 'Valor do Ressarcimento', 'Valor do Complemento',
            'ICMS Efetivo da Entrada', 'ICMS - Crédito da Operação Própria (artigo 271 do RICMS)']]


ficha_3_revizia_com_cabecalho

C:\Users\vinic\AppData\Local\Temp\ipykernel_2116\1347571090.py:94: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(inserir_linha_inicial)

,Código da Mercadoria,Número da Ordem,Data,Chave,Tipo,Série do documento,Número da nota,Código do Remetente ou Destinatário,CFOP,Número do Item no Documento XML,Quantidade (Entrada),Valor Total do ICMS Suportado na Retenção ou Antecipação por ST,Quantidade (Saída),Valor Unitário do ICMS Suportado,Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1,Fato Gerador Não Realizado - Código Enquadramento Legal = 2,Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3,Saída para Outro Estado - Código Enquadramento Legal = 4,Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0,ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência,Quantidade,Valor Unitário do Saldo,Valor Total do Saldo,Valor do Ressarcimento,Valor do Complemento,ICMS Efetivo da Entrada,ICMS - Crédito da Operação Própria (artigo 271 do RICMS)
0,001010101002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.83,1.249722,167.250357,NaN,NaN,NaN,NaN
1,001010101002,1.0,2020-03-16,35200365369985000504550060000473171100175734,1.0,006,000047317,65369985000504,5405.0,3.0,NaN,NaN,8.0,1.249722,NaN,NaN,NaN,NaN,9.997780,17.1216,125.83,1.249722,157.252577,0.0,7.123820,NaN,NaN
2,001010101002,2.0,2020-03-18,35200365369985000504550060000473911100009840,1.0,006,000047391,65369985000504,5405.0,1.0,NaN,NaN,3.0,1.249722,NaN,NaN,NaN,NaN,3.749167,8.1432,122.83,1.249722,153.503410,0.0,4.394033,NaN,NaN
3,001010101002,3.0,2020-04-24,35200465369985000504550060000483591100304419,1.0,006,000048359,65369985000504,5405.0,8.0,NaN,NaN,50.0,1.249722,NaN,NaN,NaN,NaN,62.486123,135.7200,72.83,1.249722,91.017287,0.0,73.233877,NaN,NaN
4,001010101002,4.0,2020-05-06,35200565369985000504550060000486951100123356,1.0,006,000048695,65369985000504,5405.0,19.0,NaN,NaN,10.0,1.249722,NaN,NaN,NaN,NaN,12.497225,32.5800,62.83,1.249722,78.520062,0.0,20.082775,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,VIAVE3001005,3.0,2020-10-23,35201065369985000504590003340440078578021018,1.0,000334044,007857,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.402332,NaN,NaN,NaN,NaN,0.402332,1.6788,1.00,0.402332,0.402332,0.0,0.000000,NaN,NaN
4,VIAVE3001005,4.0,2020-10-23,35201065369985000504590003340440078578021018,1.0,000334044,007857,65369985000504,5102.0,2.0,NaN,NaN,1.0,0.402332,NaN,NaN,NaN,NaN,0.402332,1.6788,0.00,NaN,0.000000,0.0,0.000000,NaN,NaN
0,VIAVE3001006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.201022,0.402044,NaN,NaN,NaN,NaN
1,VIAVE3001006,1.0,2020-06-18,35200665369985000504590003340440044091519950,1.0,000334044,004409,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.201022,NaN,NaN,NaN,NaN,0.201022,0.8388,1.00,0.201022,0.201022,0.0,0.000000,NaN,NaN
2,VIAVE3001006,2.0,2020-06-26,35200665369985000504590003340440046248265500,1.0,000334044,004624,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.201022,NaN,NaN,NaN,NaN,0.201022,0.8388,0.00,NaN,0.000000,0.0,0.000000,NaN,NaN

In [116]:
salvar_dataframe_no_s3(ficha_3_revizia_com_cabecalho,
                    bucket_name,
                    f'Cat42/{nome_empresa.title()}/Ficha 3 Revizia/ficha_3_modelo_revizia_{nome_empresa.title()}_{cnpj}.xlsx',
                                                           file_type='xlsx')

Arquivo salvo com sucesso em 'Cat42/Tateti/Ficha 3 Revizia/ficha_3_modelo_revizia_Tateti_65369985000504.xlsx'.

In [6]:
sum(teste['VLR_RESSARCIMENTO'])

2700214.5340872207

In [ ]:
import pandas as pd

# Caminho do arquivo Excel
caminho_arquivo = r"C:\Users\simas\OneDrive\Área de Trabalho\teste.xlsx"

# Carregar a planilha
df = pd.read_excel(caminho_arquivo, dtype=str)


# Função para extrair os dados de acordo com o modelo da chave
def extrair_dados(chave):
    if isinstance(chave, str) and len(chave) == 44:  # Verifica se a chave tem 44 caracteres
        modelo = chave[20:22]  # Posições 21 e 22 determinam o modelo

        if modelo == "55":  # Modelo 55 (NF-e)
            serie = chave[22:25]  # Posições 23 a 25 (3 caracteres)
            numero_nota = chave[25:34]  # Posições 26 a 34 (9 caracteres)
        elif modelo == "59":  # Modelo 59 (CFe-SAT)
            serie = chave[22:31]  # Posições 23 a 31 (9 caracteres - Número de Série do SAT)
            numero_nota = chave[31:37]  # Posições 32 a 37 (6 caracteres - Número do CFe-SAT)
        else:
            serie, numero_nota = None, None  # Caso seja um modelo diferente

        return serie, numero_nota
    return None, None


# Aplicar a função em todas as chaves e preencher as colunas
df[['Série do documento', 'Número da nota']] = df['Chave'].apply(lambda x: pd.Series(extrair_dados(x)))

# Salvar a planilha atualizada
caminho_saida = r"C:\Users\simas\OneDrive\Área de Trabalho\teste_atualizado.xlsx"
df.to_excel(caminho_saida, index=False)

print(f"Arquivo atualizado salvo em: {caminho_saida}")

In [74]:
from io import StringIO

ficha_3 = ler_arquivo_para_dataframe(bucket_name=bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
                                  file_type='xlsx')

def recalcular_digito_verificador(nfe_completa):
    # Verifica se a NF-e com o dígito verificador tem o tamanho correto
    if pd.isnull(nfe_completa) or len(nfe_completa) != 44:
        raise ValueError(f"Valor inválido na coluna 'CHV_DOC': {nfe_completa}")

    # Remove o último caractere (dígito verificador)
    nfe_sem_dv = nfe_completa[:-1]

    # Restante da lógica de cálculo do dígito verificador
    soma = 0
    peso = 2
    nfe_invertida = nfe_sem_dv[::-1]

    for digito in nfe_invertida:
        soma += int(digito) * peso
        peso += 1
        if peso > 9:
            peso = 2

    resto = soma % 11
    dv = 0 if resto == 0 or resto == 1 else 11 - resto

    return dv

# Iterate through each file in the folder
query = 'SELECT * FROM "0000" '
df_0000 = pd.read_sql_query(query, engine)
df_0000['data'] = df_0000['data'].astype(str).str.slice(0, 10)
df_0000['data'] = [datetime.strptime(x, '%d/%m/%Y').strftime('%m%Y') for x in df_0000['data']]
df_0000['COD_VER'] = ['01'] * df_0000.shape[0]
df_0000['COD_FIN'] = ['00'] * df_0000.shape[0]
df_0000 = df_0000[['empresa','registro', 'data', 'razao_social', 'cnpj', 'ie',
        'codigo_municipio', 'COD_VER', 'COD_FIN']]

cnpj_loja = df_0000[df_0000['empresa'] == cnpj]['cnpj'].values[0]

prefix = f"Cat42/{nome_empresa.title()}/Txts/Teste_CNPJ_{cnpj}/"
files = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix)

# Filtrar arquivos que começam com '1100'
filtered_files = [file['Key'] for file in files.get('Contents', []) if file['Key'].startswith(f'{prefix}1100')]

# Inicializar uma lista para armazenar os dataframes
dfs = []

# Ler e processar cada arquivo
for file_key in filtered_files:
    # Baixar o conteúdo do arquivo S3
    file_obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    file_content = file_obj['Body'].read().decode('latin-1')  # Ajuste de encoding caso necessário

    # Converter o conteúdo do arquivo para um DataFrame
    # Aqui assumimos que os arquivos têm dados separados por '|' (se for outro delimitador, ajuste conforme necessário)
    df = pd.read_csv(StringIO(file_content), sep='|',header=None,
                     names=['Cod_reg', 'Chv_doc', 'data', 'num_item', 'ind_oper', 
                             'cod_prod', 'cfop', 'qtd', 'icms_tot', 'vlr_confr', 'cod_legal'])

    # Adicionar o DataFrame à lista
    dfs.append(df)

# Concatenar todos os DataFrames em um único DataFrame
final_df = pd.concat(dfs, ignore_index=True)

df_1100_icms_tot = final_df[['Chv_doc', 'num_item', 'icms_tot']]
ficha_3_icms_tot = ficha_3[['CHV_DOC', 'NUM_ITEM', 'ICMS_TOT_PCAT']]

ficha_3_icms_tot['NUM_ITEM'] = ficha_3_icms_tot['NUM_ITEM'].astype(str)
df_1100_icms_tot['num_item'] = df_1100_icms_tot['num_item'].astype(str)

df_1100_icms_tot['Chv_item'] = df_1100_icms_tot['Chv_doc'] + '-' + df_1100_icms_tot['num_item']
ficha_3_icms_tot['CHV_ITEM'] = ficha_3_icms_tot['CHV_DOC'] + '-' + ficha_3_icms_tot['NUM_ITEM']

df_1100_icms_tot['icms_tot'] = df_1100_icms_tot['icms_tot'].str.replace(',', '.').astype(float)

merged = df_1100_icms_tot.merge(ficha_3_icms_tot[['CHV_ITEM', 'ICMS_TOT_PCAT']],
                               left_on=['Chv_item'],
                               right_on=['CHV_ITEM'])

merged = merged.drop_duplicates()

merged['Diffs'] = np.abs(merged['icms_tot'] - merged['ICMS_TOT_PCAT'])

Arquivo 'Cat42/Ladakh/Ficha 3/ficha_3_Ladakh_07318052000150_v2.xlsx' lido com sucesso!

C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ficha_3_icms_tot['NUM_ITEM'] = ficha_3_icms_tot['NUM_ITEM'].astype(str)
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1100_icms_tot['num_item'] = df_1100_icms_tot['num_item'].astype(str)
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1100_icms_tot['Chv_item'] = df_1100_icms_tot['Chv_doc'] + '-' + df_1100_icms_tot['num_item']
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ficha_3_icms_tot['CHV_ITEM'] = ficha_3_icms_tot['CHV_DOC'] + '-' + ficha_3_icms_tot['NUM_ITEM']
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\3196766653.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1100_icms_tot['icms_tot'] = df_1100_icms_tot['icms_tot'].str.replace(',', '.').astype(float)

In [114]:
teste = final_df[final_df['Chv_doc'] == '35220142750994000103550010000000091900080107']
teste

,Cod_reg,Chv_doc,data,num_item,ind_oper,cod_prod,cfop,qtd,icms_tot,vlr_confr,cod_legal
9,1100,35220142750994000103550010000000091900080107,30012022,74,0,1025200,1411,"12,000","25,22",NaN,1.0
141,1100,35220142750994000103550010000000091900080107,30012022,32,0,11025,1411,"27,000","32,83",NaN,1.0
159,1100,35220142750994000103550010000000091900080107,30012022,23,0,11026,1411,"20,000","32,83",NaN,1.0
180,1100,35220142750994000103550010000000091900080107,30012022,29,0,11027,1411,"20,000","32,83",NaN,1.0
203,1100,35220142750994000103550010000000091900080107,30012022,22,0,11028,1411,"19,000","32,83",NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2729,1100,35220142750994000103550010000000091900080107,30012022,126,0,91019,1411,"42,000","0,00",NaN,1.0
2803,1100,35220142750994000103550010000000091900080107,30012022,77,0,922600,1411,"28,000","29,54",NaN,1.0
2813,1100,35220142750994000103550010000000091900080107,30012022,82,0,956001,1411,"18,000","21,94",NaN,1.0
2814,1100,35220142750994000103550010000000091900080107,30012022,81,0,956002,1411,"37,000","0,00",NaN,1.0
2815,1100,35220142750994000103550010000000091900080107,30012022,80,0,956003,1411,"48,000","0,00",NaN,1.0

In [120]:
final_df['cfop'] = final_df['cfop'].astype(str)
final_df['cod_legal'] = final_df['cod_legal'].astype(float)

In [126]:
teste[(teste['cfop'].isin(['5405', '1411', '5409', '5403', '5401'])) & (final_df['cod_legal'] >= 1) & (final_df['vlr_confr'].isnull())]

C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\2231388995.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  teste[(teste['cfop'].isin(['5405', '1411', '5409', '5403', '5401'])) & (final_df['cod_legal'] >= 1) & (final_df['vlr_confr'].isnull())]

,Cod_reg,Chv_doc,data,num_item,ind_oper,cod_prod,cfop,qtd,icms_tot,vlr_confr,cod_legal
9,1100,35220142750994000103550010000000091900080107,30012022,74,0,1025200,1411,"12,000","25,22",NaN,1.0
141,1100,35220142750994000103550010000000091900080107,30012022,32,0,11025,1411,"27,000","32,83",NaN,1.0
159,1100,35220142750994000103550010000000091900080107,30012022,23,0,11026,1411,"20,000","32,83",NaN,1.0
180,1100,35220142750994000103550010000000091900080107,30012022,29,0,11027,1411,"20,000","32,83",NaN,1.0
203,1100,35220142750994000103550010000000091900080107,30012022,22,0,11028,1411,"19,000","32,83",NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2729,1100,35220142750994000103550010000000091900080107,30012022,126,0,91019,1411,"42,000","0,00",NaN,1.0
2803,1100,35220142750994000103550010000000091900080107,30012022,77,0,922600,1411,"28,000","29,54",NaN,1.0
2813,1100,35220142750994000103550010000000091900080107,30012022,82,0,956001,1411,"18,000","21,94",NaN,1.0
2814,1100,35220142750994000103550010000000091900080107,30012022,81,0,956002,1411,"37,000","0,00",NaN,1.0
2815,1100,35220142750994000103550010000000091900080107,30012022,80,0,956003,1411,"48,000","0,00",NaN,1.0